version: '3'

services:

    selenoid:
#        image: "dockerhub.repo.corp.tander.ru/aerokube/selenoid:latest"
        image: "dockerhub.repo.corp.tander.ru/aerokube/selenoid:1.10.5"
        container_name: selenoid
        network_mode: bridge
        restart: always
        ports:
            - "4444:4444"
        volumes:
            - "/opt/selenoid/:/etc/selenoid/"
            - "/opt/selenoid/logs:/opt/selenoid/logs"
            - "/opt/selenoid/video:/opt/selenoid/video"
            - "/var/run/docker.sock:/var/run/docker.sock"
        environment:
            - OVERRIDE_VIDEO_OUTPUT_DIR=/opt/selenoid/video
        command: -limit 16
                 -timeout 3m
                 -session-delete-timeout 3m
                 -session-attempt-timeout 3m
                 -service-startup-timeout 3m
                 -conf /etc/selenoid/browsers.json
                 -video-output-dir /opt/selenoid/video
                 -log-output-dir /opt/selenoid/logs

    selenoid-ui:
        image: "dockerhub.repo.corp.tander.ru/aerokube/selenoid-ui:1.10.4"
        container_name: selenoid-ui
        network_mode: bridge
        restart: always
        links:
            - selenoid
        ports:
            - "8080:8080"
        command: ["--selenoid-uri", "http://selenoid:4444"]

    mariadb:
        image: docker.io/bitnami/mariadb:10.3
        environment:
          # ALLOW_EMPTY_PASSWORD is recommended only for development.
          - ALLOW_EMPTY_PASSWORD=yes
          - MARIADB_USER=bn_opencart
          - MARIADB_DATABASE=bitnami_opencart
        volumes:
          - 'mariadb_data:/bitnami/mariadb'

    opencart:
        image: docker.io/bitnami/opencart:3
        ports:
          - '80:8080'
          - '443:8443'
        environment:
          - OPENCART_HOST=localhost
          - OPENCART_DATABASE_HOST=mariadb
          - OPENCART_DATABASE_PORT_NUMBER=3306
          - OPENCART_DATABASE_USER=bn_opencart
          - OPENCART_DATABASE_NAME=bitnami_opencart
          # ALLOW_EMPTY_PASSWORD is recommended only for development.
          - ALLOW_EMPTY_PASSWORD=yes
        volumes:
          - 'opencart_data:/bitnami/opencart'
          - 'opencart_storage_data:/bitnami/opencart_storage/'
        depends_on:
          - mariadb

volumes:
    mariadb_data:
        driver: local
    opencart_data:
        driver: local
    opencart_storage_data:
        driver: local
